// <auto-generated />
namespace Project1640.EF
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddValidate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddValidate));
        
        string IMigrationMetadata.Id
        {
            get { return "202203310938271_AddValidate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
