// <auto-generated />
namespace Project1640.EF
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialCreate));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:Project1640/EF/202203250945003_InitialCreate.Designer.cs
            get { return "202203250945003_InitialCreate"; }
=======
            get { return "202203301936308_InitialCreate"; }
>>>>>>> 2d427c3a06b75ea32b86330a825df742106df8a6:Project1640/EF/202203301936308_InitialCreate.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
